//-------------------------------------------------------------------------------
// <copyright file="GlobalSuppressions.cs" company="Appccelerate">
//   Copyright (c) 2008-2013
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// </copyright>
//-------------------------------------------------------------------------------

// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Appccelerate.EventBroker.Sample.Program.#Main()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1824:MarkAssembliesWithNeutralResourcesLanguage")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Ui", Scope = "member", Target = "Appccelerate.EventBroker.Sample.Pong.#UiFromUiEvent")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Ui", Scope = "member", Target = "Appccelerate.EventBroker.Sample.Pong.#UiFromAsyncEvent")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Ui", Scope = "member", Target = "Appccelerate.EventBroker.Sample.Pong.#HandlePingUiFromUiThread(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Ui", Scope = "member", Target = "Appccelerate.EventBroker.Sample.Pong.#HandlePingUiFromAsync(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Ui", Scope = "member", Target = "Appccelerate.EventBroker.Sample.Ping.#UiFromUiEvent")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Ui", Scope = "member", Target = "Appccelerate.EventBroker.Sample.Ping.#UiFromAsyncEvent")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Ui", Scope = "member", Target = "Appccelerate.EventBroker.Sample.Ping.#HandleUiFromUi(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Ui", Scope = "member", Target = "Appccelerate.EventBroker.Sample.Ping.#HandleUiFromAsync(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.DateTime.ToString(System.String)", Scope = "member", Target = "Appccelerate.EventBroker.Sample.Ping.#timer_Tick(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Windows.Forms.Control.set_Text(System.String)", Scope = "member", Target = "Appccelerate.EventBroker.Sample.Ping.#InitializeComponent()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Windows.Forms.Control.set_Text(System.String)", Scope = "member", Target = "Appccelerate.EventBroker.Sample.Ping.#HandleUiFromUi(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Windows.Forms.Control.set_Text(System.String)", Scope = "member", Target = "Appccelerate.EventBroker.Sample.Ping.#HandleUiFromAsync(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1053:StaticHolderTypesShouldNotHaveConstructors", Scope = "type", Target = "Appccelerate.EventBroker.Sample.EventTopics")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Appccelerate.EventBroker.Sample.DebugLogger.#AddedPublication(Appccelerate.EventBroker.Internals.IEventTopicInfo,Appccelerate.EventBroker.Internals.IPublication)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Appccelerate.EventBroker.Sample.DebugLogger.#AddedSubscription(Appccelerate.EventBroker.Internals.IEventTopicInfo,Appccelerate.EventBroker.Internals.ISubscription)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Appccelerate.EventBroker.Sample.DebugLogger.#AddedSubscription(Appccelerate.EventBroker.Internals.IEventTopicInfo,Appccelerate.EventBroker.Internals.ISubscription)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Appccelerate.EventBroker.Sample.DebugLogger.#CreatedTopic(Appccelerate.EventBroker.Internals.IEventTopicInfo)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Appccelerate.EventBroker.Sample.DebugLogger.#FiredEvent(Appccelerate.EventBroker.Internals.IEventTopicInfo,Appccelerate.EventBroker.Internals.IPublication,System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Appccelerate.EventBroker.Sample.DebugLogger.#FiredEvent(Appccelerate.EventBroker.Internals.IEventTopicInfo,Appccelerate.EventBroker.Internals.IPublication,System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Appccelerate.EventBroker.Sample.DebugLogger.#FiringEvent(Appccelerate.EventBroker.Internals.IEventTopicInfo,Appccelerate.EventBroker.Internals.IPublication,System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Appccelerate.EventBroker.Sample.DebugLogger.#RelayedEvent(Appccelerate.EventBroker.Internals.IEventTopicInfo,Appccelerate.EventBroker.Internals.IPublication,Appccelerate.EventBroker.Internals.ISubscription,Appccelerate.EventBroker.IHandler,System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Appccelerate.EventBroker.Sample.DebugLogger.#RelayedEvent(Appccelerate.EventBroker.Internals.IEventTopicInfo,Appccelerate.EventBroker.Internals.IPublication,Appccelerate.EventBroker.Internals.ISubscription,Appccelerate.EventBroker.IHandler,System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "2", Scope = "member", Target = "Appccelerate.EventBroker.Sample.DebugLogger.#RelayedEvent(Appccelerate.EventBroker.Internals.IEventTopicInfo,Appccelerate.EventBroker.Internals.IPublication,Appccelerate.EventBroker.Internals.ISubscription,Appccelerate.EventBroker.IHandler,System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Appccelerate.EventBroker.Sample.DebugLogger.#RelayingEvent(Appccelerate.EventBroker.Internals.IEventTopicInfo,Appccelerate.EventBroker.Internals.IPublication,Appccelerate.EventBroker.Internals.ISubscription,Appccelerate.EventBroker.IHandler,System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Appccelerate.EventBroker.Sample.DebugLogger.#RelayingEvent(Appccelerate.EventBroker.Internals.IEventTopicInfo,Appccelerate.EventBroker.Internals.IPublication,Appccelerate.EventBroker.Internals.ISubscription,Appccelerate.EventBroker.IHandler,System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "2", Scope = "member", Target = "Appccelerate.EventBroker.Sample.DebugLogger.#RelayingEvent(Appccelerate.EventBroker.Internals.IEventTopicInfo,Appccelerate.EventBroker.Internals.IPublication,Appccelerate.EventBroker.Internals.ISubscription,Appccelerate.EventBroker.IHandler,System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Appccelerate.EventBroker.Sample.DebugLogger.#RemovedPublication(Appccelerate.EventBroker.Internals.IEventTopicInfo,Appccelerate.EventBroker.Internals.IPublication)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Appccelerate.EventBroker.Sample.DebugLogger.#RemovedPublication(Appccelerate.EventBroker.Internals.IEventTopicInfo,Appccelerate.EventBroker.Internals.IPublication)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Appccelerate.EventBroker.Sample.DebugLogger.#RemovedSubscription(Appccelerate.EventBroker.Internals.IEventTopicInfo,Appccelerate.EventBroker.Internals.ISubscription)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Appccelerate.EventBroker.Sample.DebugLogger.#RemovedSubscription(Appccelerate.EventBroker.Internals.IEventTopicInfo,Appccelerate.EventBroker.Internals.ISubscription)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.IO.StringWriter.#ctor(System.Text.StringBuilder)", Scope = "member", Target = "Appccelerate.EventBroker.Sample.DebugLogger.#SkippedEvent(Appccelerate.EventBroker.Internals.IEventTopicInfo,Appccelerate.EventBroker.Internals.IPublication,Appccelerate.EventBroker.Internals.ISubscription,System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Appccelerate.EventBroker.Sample.DebugLogger.#SkippedEvent(Appccelerate.EventBroker.Internals.IEventTopicInfo,Appccelerate.EventBroker.Internals.IPublication,Appccelerate.EventBroker.Internals.ISubscription,System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Appccelerate.EventBroker.Sample.DebugLogger.#SubscriberExceptionOccurred(Appccelerate.EventBroker.Internals.IEventTopicInfo,System.Exception,Appccelerate.EventBroker.ExceptionHandlingContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Appccelerate.EventBroker.Sample.DebugLogger.#AddedPublication(Appccelerate.EventBroker.Internals.IEventTopicInfo,Appccelerate.EventBroker.Internals.IPublication)")]
