//-------------------------------------------------------------------------------
// <copyright file="GlobalSuppressions.cs" company="Appccelerate">
//   Copyright (c) 2008-2013
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// </copyright>
//-------------------------------------------------------------------------------

// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Appccelerate.SourceTemplates.Log4Net.AsyncWorkerLogExtension.#CancellingExecution(Appccelerate.Async.AsyncWorker,System.ComponentModel.DoWorkEventHandler)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "3", Scope = "member", Target = "Appccelerate.SourceTemplates.Log4Net.AsyncWorkerLogExtension.#CompletedExecution(Appccelerate.Async.AsyncWorker,System.ComponentModel.DoWorkEventHandler,System.ComponentModel.RunWorkerCompletedEventHandler,System.ComponentModel.RunWorkerCompletedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Appccelerate.SourceTemplates.Log4Net.AsyncWorkerLogExtension.#ReportProgress(Appccelerate.Async.AsyncWorker,System.ComponentModel.DoWorkEventHandler,System.ComponentModel.ProgressChangedEventHandler,System.Object)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Appccelerate.SourceTemplates.Log4Net.AsyncWorkerLogExtension.#StartedExecution(Appccelerate.Async.AsyncWorker,System.ComponentModel.DoWorkEventHandler,System.Object)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Appccelerate.SourceTemplates.Log4Net.EvaluationEngineLogExtension.#FoundAnswer(Appccelerate.EvaluationEngine.Context)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Appccelerate.SourceTemplates.Log4Net.EventBrokerLogExtension.#AddedPublication(Appccelerate.EventBroker.IEventTopicInfo,Appccelerate.EventBroker.IPublication)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Appccelerate.SourceTemplates.Log4Net.EventBrokerLogExtension.#AddedPublication(Appccelerate.EventBroker.IEventTopicInfo,Appccelerate.EventBroker.IPublication)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Appccelerate.SourceTemplates.Log4Net.EventBrokerLogExtension.#AddedSubscription(Appccelerate.EventBroker.IEventTopicInfo,Appccelerate.EventBroker.ISubscription)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Appccelerate.SourceTemplates.Log4Net.EventBrokerLogExtension.#AddedSubscription(Appccelerate.EventBroker.IEventTopicInfo,Appccelerate.EventBroker.ISubscription)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Appccelerate.SourceTemplates.Log4Net.EventBrokerLogExtension.#CreatedTopic(Appccelerate.EventBroker.IEventTopicInfo)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Appccelerate.SourceTemplates.Log4Net.EventBrokerLogExtension.#FiredEvent(Appccelerate.EventBroker.IEventTopicInfo,Appccelerate.EventBroker.IPublication,System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Appccelerate.SourceTemplates.Log4Net.EventBrokerLogExtension.#FiredEvent(Appccelerate.EventBroker.IEventTopicInfo,Appccelerate.EventBroker.IPublication,System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Appccelerate.SourceTemplates.Log4Net.EventBrokerLogExtension.#FiringEvent(Appccelerate.EventBroker.IEventTopicInfo,Appccelerate.EventBroker.IPublication,System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Appccelerate.SourceTemplates.Log4Net.EventBrokerLogExtension.#RelayedEvent(Appccelerate.EventBroker.IEventTopicInfo,Appccelerate.EventBroker.IPublication,Appccelerate.EventBroker.ISubscription,Appccelerate.EventBroker.IHandler,System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Appccelerate.SourceTemplates.Log4Net.EventBrokerLogExtension.#RelayedEvent(Appccelerate.EventBroker.IEventTopicInfo,Appccelerate.EventBroker.IPublication,Appccelerate.EventBroker.ISubscription,Appccelerate.EventBroker.IHandler,System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "2", Scope = "member", Target = "Appccelerate.SourceTemplates.Log4Net.EventBrokerLogExtension.#RelayedEvent(Appccelerate.EventBroker.IEventTopicInfo,Appccelerate.EventBroker.IPublication,Appccelerate.EventBroker.ISubscription,Appccelerate.EventBroker.IHandler,System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Appccelerate.SourceTemplates.Log4Net.EventBrokerLogExtension.#RelayingEvent(Appccelerate.EventBroker.IEventTopicInfo,Appccelerate.EventBroker.IPublication,Appccelerate.EventBroker.ISubscription,Appccelerate.EventBroker.IHandler,System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Appccelerate.SourceTemplates.Log4Net.EventBrokerLogExtension.#RelayingEvent(Appccelerate.EventBroker.IEventTopicInfo,Appccelerate.EventBroker.IPublication,Appccelerate.EventBroker.ISubscription,Appccelerate.EventBroker.IHandler,System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "2", Scope = "member", Target = "Appccelerate.SourceTemplates.Log4Net.EventBrokerLogExtension.#RelayingEvent(Appccelerate.EventBroker.IEventTopicInfo,Appccelerate.EventBroker.IPublication,Appccelerate.EventBroker.ISubscription,Appccelerate.EventBroker.IHandler,System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Appccelerate.SourceTemplates.Log4Net.EventBrokerLogExtension.#RemovedPublication(Appccelerate.EventBroker.IEventTopicInfo,Appccelerate.EventBroker.IPublication)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Appccelerate.SourceTemplates.Log4Net.EventBrokerLogExtension.#RemovedPublication(Appccelerate.EventBroker.IEventTopicInfo,Appccelerate.EventBroker.IPublication)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Appccelerate.SourceTemplates.Log4Net.EventBrokerLogExtension.#RemovedSubscription(Appccelerate.EventBroker.IEventTopicInfo,Appccelerate.EventBroker.ISubscription)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Appccelerate.SourceTemplates.Log4Net.EventBrokerLogExtension.#RemovedSubscription(Appccelerate.EventBroker.IEventTopicInfo,Appccelerate.EventBroker.ISubscription)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Appccelerate.SourceTemplates.Log4Net.EventBrokerLogExtension.#SkippedEvent(Appccelerate.EventBroker.IEventTopicInfo,Appccelerate.EventBroker.IPublication,Appccelerate.EventBroker.ISubscription,System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Appccelerate.SourceTemplates.Log4Net.EventBrokerLogExtension.#SubscriberExceptionOccurred(Appccelerate.EventBroker.IEventTopicInfo,System.Exception,Appccelerate.EventBroker.Exceptions.ExceptionHandlingContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Appccelerate.SourceTemplates.Log4Net.UserInterfaceThreadSynchronizerLogExtension.Log(System.String,System.Int32,System.String,System.Delegate)", Scope = "member", Target = "Appccelerate.SourceTemplates.Log4Net.UserInterfaceThreadSynchronizerLogExtension.#LogAsynchronous(System.Delegate,System.Int32,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Appccelerate.SourceTemplates.Log4Net.UserInterfaceThreadSynchronizerLogExtension.Log(System.String,System.Int32,System.String,System.Delegate)", Scope = "member", Target = "Appccelerate.SourceTemplates.Log4Net.UserInterfaceThreadSynchronizerLogExtension.#LogSynchronous(System.Delegate,System.Int32,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Appccelerate.SourceTemplates.Log4Net.UserInterfaceThreadSynchronizerLogExtension.#LogSynchronous`1(System.Delegate,System.Int32,System.String,!!0)")]
